-- Migration: Add inv_id column to robokassa_invoices table
-- Execute in Supabase SQL Editor
-- Idempotent - safe to run multiple times
--
-- Purpose: Add a dedicated int32 inv_id column for Robokassa InvId.
-- Robokassa requires InvId to be within int32 range (1..2147483647).
-- This column is auto-generated and guaranteed to be within range.

-- ============================================================================
-- Step 1: Add inv_id column if it doesn't exist
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'robokassa_invoices' 
    AND column_name = 'inv_id'
  ) THEN
    -- Add inv_id column with auto-increment (int4 = int32)
    ALTER TABLE robokassa_invoices 
    ADD COLUMN inv_id INT4 GENERATED BY DEFAULT AS IDENTITY;
    
    -- Create unique index on inv_id
    CREATE UNIQUE INDEX IF NOT EXISTS idx_robokassa_invoices_inv_id 
    ON robokassa_invoices(inv_id);
    
    -- Backfill existing rows with sequential values starting from 1
    -- This ensures all existing rows have a valid inv_id
    WITH numbered_rows AS (
      SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) as rn
      FROM robokassa_invoices
      WHERE inv_id IS NULL
    )
    UPDATE robokassa_invoices
    SET inv_id = numbered_rows.rn
    FROM numbered_rows
    WHERE robokassa_invoices.id = numbered_rows.id;
    
    -- Make inv_id NOT NULL after backfill
    ALTER TABLE robokassa_invoices 
    ALTER COLUMN inv_id SET NOT NULL;
    
    RAISE NOTICE 'Added inv_id column and backfilled existing rows';
  ELSE
    RAISE NOTICE 'Column inv_id already exists';
  END IF;
END $$;

-- ============================================================================
-- Step 2: Add constraint to ensure inv_id is within int32 range
-- ============================================================================

-- Add check constraint to ensure inv_id is within valid range
ALTER TABLE robokassa_invoices 
DROP CONSTRAINT IF EXISTS check_inv_id_range;

ALTER TABLE robokassa_invoices 
ADD CONSTRAINT check_inv_id_range 
CHECK (inv_id >= 1 AND inv_id <= 2147483647);

-- ============================================================================
-- Step 3: Update comments
-- ============================================================================

COMMENT ON COLUMN robokassa_invoices.inv_id IS 'Auto-generated int32 value used as Robokassa InvId. Must be within range 1..2147483647. This is separate from id (which can be larger).';

-- ============================================================================
-- Step 4: CRITICAL - Reload PostgREST schema cache
-- ============================================================================

SELECT pg_notify('pgrst', 'reload schema');
